apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: centos
        image: centos
        imagePullPolicy: Always
